### ISSUE TITLE
chore: typed returns for MultiPassBox.get_identity(...) in typescript

### ISSUE THREAD

**Issue by ashneverdawn** [Satellite-im/warp-wasm#9]
When `MultiPassBox.get_identity(...)` is exported to typescript, the return type is `Promise<any>`
We want `any` to be typed. (In rust it's a `Vec<Identity>`). 

Furthermore, consider splitting `.get_identity(...)` into separate functions for it's variants (`DID`, `DIDList`, `Username`) so that `DID` and `Username` variants can return just an `Identity` instead of a `Vec<Identity>` with a single element.

**Comment by dariusc93** [comment]
Given that `MultiPass::get_identity` is now returns a stream, we could probably convert the exported function to return an asynciter for the stream side (by default) and have a separate function for a single identity. See https://github.com/Satellite-im/Warp/pull/554

**Comment by Flemmli97** [comment]
shouldve been addressed in 011d9df4cae2fd60b44ea920baa3ad07a3131e82
